### ISSUE TITLE
Crashes when there's a switch through with no statement in it

### ISSUE THREAD

**Issue by Minemobs** [mike-lischke/java2typescript#17]
Java2Typescript crashes when it encounters a switch fall through with no code in it.
When trying to convert the example code, Java2Typescript crashes with this error:
```
Converting 1 files...
Converting: /home/minemobs/Projects/ts/ESC/test/src/Main.java...file:///tmp/bunx-1000-java2typescript@latest/node_modules/java2typescript/output/src/JavaFileSymbolTable.js:405
            const switchExpression = statementContext?.parExpression();
                                                       ^

TypeError: statementContext?.parExpression is not a function
    at JavaFileSymbolTable.resolveSwitchLabel (file:///tmp/bunx-1000-java2typescript@latest/node_modules/java2typescript/output/src/JavaFileSymbolTable.js:405:56)
    at JavaFileSymbolTable.getQualifiedSymbol (file:///tmp/bunx-1000-java2typescript@latest/node_modules/java2typescript/output/src/JavaFileSymbolTable.js:65:25)
    at JavaFileSource.getQualifiedSymbol (file:///tmp/bunx-1000-java2typescript@latest/node_modules/java2typescript/output/src/JavaFileSource.js:31:33)
    at FileProcessor.resolveType (file:///tmp/bunx-1000-java2typescript@latest/node_modules/java2typescript/output/src/conversion/FileProcessor.js:3263:34)
    at FileProcessor.processPrimary (file:///tmp/bunx-1000-java2typescript@latest/node_modules/java2typescript/output/src/conversion/FileProcessor.js:2292:39)
    at FileProcessor.processExpression (file:///tmp/bunx-1000-java2typescript@latest/node_modules/java2typescript/output/src/conversion/FileProcessor.js:1709:37)
    at FileProcessor.processSwitchLabel (file:///tmp/bunx-1000-java2typescript@latest/node_modules/java2typescript/output/src/conversion/FileProcessor.js:2603:18)
    at file:///tmp/bunx-1000-java2typescript@latest/node_modules/java2typescript/output/src/conversion/FileProcessor.js:2458:45
    at Array.forEach (<anonymous>)
    at FileProcessor.processStatement (file:///tmp/bunx-1000-java2typescript@latest/node_modules/java2typescript/output/src/conversion/FileProcessor.js:2457:43)

Node.js v18.15.0
```

Example of Java code:
```java
import java.util.concurrent.TimeUnit;

public class Main {
    public int doSomething(TimeUnit unit) {
        switch(unit) {
            case DAYS:
            case HOURS:
            case SECONDS:
                return 1;
            //Crashes after adding this
            case MILLISECONDS:
            case MICROSECONDS:
        }
        return 0;
    }
}
```

**Comment by mike-lischke** [comment]
Alright, that needs a check. Thanks.
